services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r authentication/requirements.txt
    startCommand: cd authentication && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2 